.PHONY: help

help:
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

install: ## Install symfony project
	@echo "Installing Symfony project"
	@composer install
	@php bin/console doctrine:database:create --connection=default
	@php bin/console assets:install

rebuild: ## Rebuild project
	@php bin/console doctrine:database:drop --force --connection=default
	@php bin/console doctrine:database:create --connection=default
	@php bin/console doctrine:schema:update --force
	@php bin/console doctrine:fixtures:load -n

start: ## start api
	symfony serve
